name: Battlegrounds
main: com.nitrikx.minecraft.bukkit.battlegrounds.Battlegrounds
version: 0.1
description: >
             Battlegrounds
commands:
    bg:
        description: Get help of battlegrounds.
        permission: battlegrounds.basic
        usage: "Get list of commands : /bg [help]"
permissions:
    battlegrounds.*:
        description: Can manage all the battlegrounds options.
        default: op
        children:
            battlegrounds.team.*: true
            battlegrounds.version: true
            battlegrounds.basic: true
    battlegrounds.basic:
        description: Basic permissions for Battlegrounds mod.
    battlegrounds.version:
        description: Get version of Battlegrounds.
    battlegrounds.team.*:
        description: Can manage teams.
        children:
            battlegrounds.team.create: true
            battlegrounds.team.delete: true
            battlegrounds.team.manageplayer: true
    battlegrounds.team.manageplayers:
        description: Can manage player into teams.
        children:
            battlegrounds.team.player.add: true
            battlegrounds.team.player.remove: true
    battlegrounds.team.create:
        description: Can create a team.
    battlegrounds.team.delete:
        description: Can delete a team.
    battlegrounds.team.player.add:
        description: Can add a player to a team.
    battlegrounds.team.player.remove:
        description: Can remove a player from a team.