name: Battlegrounds
main: com.nitrikx.minecraft.bukkit.battlegrounds.Battlegrounds
version: 0.1
description: >
             Battlegrounds
commands:
   bg:
      description: Get help of battlegrounds.
      permission: battlegrounds.basic
      usage: "Get list of commands : /bg [help]"